# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 网站
title: sterben110的博客                 #网站标题
subtitle: ''                            #网站副标题
description: ''                         #网站描述
keywords:                               #网站的关键词。使用半角逗号 , 分隔多个关键词。
author: chenbin                         #作者
language: zh-Hans                       #网站使用的语言
timezone: ''                            #网站时区

# 网址
url: http://yoursite.com                #网址
root: /                                 #网站根目录
permalink: :year/:month/:day/:title/    #文章的 永久链接 格式
permalink_defaults:                     #永久链接中各部分的默认值
pretty_urls:
  trailing_index: true        #是否在永久链接中保留尾部的 index.html，设置为 false 时去除
  trailing_html: true         #是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)

# 目录
source_dir: source          #资源文件夹
public_dir: public          #公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags               #标签文件夹
archive_dir: archives       #归档文件夹
category_dir: categories    #分类文件夹
code_dir: downloads/code
i110n_dir: :lang
skip_render:                #跳过指定文件的渲染。匹配到的文件将会被不做改动地复制到 public 目录中。

# 文章
new_post_name: :title.md    #hexo new [title]时新文章的文件名称
default_layout: post        #新建文章时的预设布局
auto_spacing: false         #在中文和英文之间加入空格
titlecase: false            #把标题转换为 title case
external_link:              #在新标签中打开链接
  enable: true 
  field: site               #对整个网站（site）生效或仅对文章（post）生效
  exclude: ''
filename_case: 0            #把博客名称改成小写/大写（1,2）
render_drafts: false        #是否显示草稿
post_asset_folder: false    #是否启用资源文件夹（用来存放相对路径图片或文件）
relative_link: false        #把链接改为与根目录的相对位址
future: true
highlight:
  enable: true              #是否开启代码高亮
  line_number: true         #是否增加代码行号
  auto_detect: false        #自动判断代码语言
  tab_replace: ''
  wrap: true
  hljs: false

# 主页设置
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:            #首页博客分布
  path: ''                  #博客的默认路径
  per_page: 10              #每页博客数量上限
  order_by: -updated        #博客排序

# 分类与标签
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD #博客日期格式
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# 分页
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:  
  type: git
  repository: git@github.com:sterben110/sterben110.github.io.git
  branch: master

search:
  path: search.xml
  field: post
  format: html
  limit: 10000